apiVersion: v1
kind: Secret
metadata:
name: wailsalutem-backend-secrets
namespace: wailsalutem-suite
type: Opaque
stringData:
DB_USER: <db-user>
DB_PASSWORD: <db-password>
RABBITMQ_USER: <rabbitmq-user>
RABBITMQ_PASSWORD: <rabbitmq-password>
KEYCLOAK_ADMIN_CLIENT_SECRET: <keycloak-admin-secret>