apiVersion: v1
kind: Service
metadata:
  name: care-session-service
  namespace: wailsalutem-suite
spec:
  selector:
    app: care-session-service
  ports:
    - name: http
      port: 80
      targetPort: 8000